version: "2"
services:
  php-fpm:
    image: dockerkit/php-fpm:7.0.12-gd-imagick
    volumes:
     - ./src:/srv/web
     - node_modules:/srv/web/node_modules
    working_dir: /srv/web
    hostname: docker-php-fpm
    ports:
     - "9006:9000"
    user: "${UID}"
    links:
     - database
  nginx:
    image: nginx:1.10.1-alpine
    volumes:
     - ./src:/srv/web
     - ./config/docker/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - "8089:80"
    links:
     - php-fpm:fcgi
  database:
    image: mariadb:10.1.17
    volumes:
     - ./src/database/init/mysql:/docker-entrypoint-initdb.d
    environment:
     - MYSQL_DATABASE=initial
     - MYSQL_ROOT_PASSWORD=mysql
    expose:
     - "3306"
    ports:
     - "3305:3306"
volumes:
    node_modules: {}
